# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]


jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    
    
    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.SECRETS}}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.SECRETS}} | sed
